export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";
export const STUDENT_IS_ABSENT = "STUDENT_IS_ABSENT";
export const STUDENT_IS_PRESENT = "STUDENT_IS_PRESENT";
export const DELETE_STUDENT_DATA = "DELETE_STUDENT_DATA";
export const FETCH_STUDENTS_DATA = "FETCH_STUDENTS_DATA";
export const FETCH_SINGLE_STUDENT_DATA = "FETCH_SINGLE_STUDENT_DATA";
